### ISSUE TITLE
Each endpoint support allowed methods?

### ISSUE THREAD

**Issue by juunone** [julien-lafont/Mocky#104]
hi, i'm very useful to use mocky

- first question 
> i want to use with each endpoint only support allowed methods.
can i setting that [mocky](https://designer.mocky.io/design) in `GUI`?
or have support in roadmap?

- second question 
> have plan to support json file to upload response body

thank you.

**Comment by julien-lafont** [comment]
Hello,

It's not possible to restrict a mocky URI to a specific METHOD. All METHODS are allowed.
No plan to change that at short terms.

For the second question, I'll accept a PR to set the body by drag-dropping a file
