### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by onigetoc** [julien-lafont/Mocky#13]
There's not much explanation about No 'Access-Control-Allow-Origin'
i use a getjson on a exemple on Jsfiddle. it's working.
http://jsfiddle.net/ZjUgY/
i copy paste de json file and did my own with the same response on mocky.io.
but mine give me a No 'Access-Control-Allow-Origin'
But it's the exacte same json file.

**Comment by gilleard** [comment]
You need to manually specify the header using advanced mode (with the warnings mentioned here https://github.com/studiodev/Mocky/issues/7#issuecomment-142230155) - just realised myself.

**Comment by daniloprates** [comment]
@gilleard what should I specify?

**Comment by gilleard** [comment]
@daniloprates adding a custom header with a name of `Access-Control-Allow-Origin` and a value of `*` (or whatever hostname you need) will avoid the problem while you're using Mocky.

The warning is that obviously you'd need to replicate this in production, which may not be possible if it's a third-party API.

**Comment by julien-lafont** [comment]
Hello,

CORS preflight requests are now automatically accepted by Mocky server. It's no longer required to add the `Access-Control-Allow-Origin` header.

Thanks for your feedback.

**Comment by elyazinho** [comment]
hi there's an issue with CORS preflight requests again

**Comment by tobemaster56** [comment]
A few days ago I was using mocky with no problems, but now I get an error

![image](https://user-images.githubusercontent.com/8998761/160335753-f8ac6a9a-b540-41ad-a43b-17bf776297c7.png)

CORS preflight requests are OK，but the request is not ok

![image](https://user-images.githubusercontent.com/8998761/160335917-33d64ba7-4f48-4caf-8f25-2b2c09d36f0e.png)

```bash
Access to XMLHttpRequest at 'https://www.mocky.io/v2/5cc8019d300000980a055e76' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
even if i set Access-Control-Allow-Origin = * in header  , the error is still there
![image](https://user-images.githubusercontent.com/8998761/160336216-d1cbcfaf-3db6-4ba7-be78-60719725a3f6.png)


How to reproduce the problem，try the follow

https://ant.design/components/upload/#components-upload-demo-basic
