### ISSUE TITLE
Ability to delay the response (feature request)

### ISSUE THREAD

**Issue by kunwardeepsingh** [julien-lafont/Mocky#14]
It would be helpful to us if there is an option to specify the time delay in the response. Thanks!

**Comment by suprcool01** [comment]
+1

**Comment by rsp** [comment]
@kunwardeepsingh Any update on the status of this feature request?

**Comment by julien-lafont** [comment]
Hello,

With a huge lag, i've added this feature. You can delay the response with `?mocky-delay=100ms`.

**Comment by julien-lafont** [comment]
And thanks for your feedbacks :)

**Comment by kunwardeeps** [comment]
Thanks for adding this!
