### ISSUE TITLE
Synchronous XHR Requests Fail

### ISSUE THREAD

**Issue by coreybutler** [julien-lafont/Mocky#18]
A standard **a**synchronous XHR request works, such as typing a mocky URL into a browser:

![image](https://cloud.githubusercontent.com/assets/770982/22792714/46a8e320-eeb3-11e6-811f-79cff4b62cc9.png)

However, **synchronous** requests fail. The most glaringly obvious place to recreate the error is in Postman:

![image](https://cloud.githubusercontent.com/assets/770982/22792542/bf0d084c-eeb2-11e6-8429-6a68a108a3b5.png)

Postman just hangs. When I run a raw XHR request against the [URL](http://www.mocky.io/v2/577959d31300006418bc3ef7), the error indicates a failure to load.

![image](https://cloud.githubusercontent.com/assets/770982/22792623/043de2e2-eeb3-11e6-8254-b7e9a6787f5f.png)

In most cases, this has to do with a CORS header, but it's hard to inspect the request when there is no response, so I can't provide any further details. In circumstances where an HTTPS request is made, this is further complicated by the fact the mocky.io SSL certificate is invalid.

**Comment by julien-lafont** [comment]
Thanks for your feedback.

I'll work on making mocky SSL compliance (not easy with gandi & heroku...)
