### ISSUE TITLE
Error :"Please wait This application is starting, you will be redirected once it is ready"

### ISSUE THREAD

**Issue by NimaaZx** [julien-lafont/Mocky#186]
Hi, Thanks to developers. there is a world wide problem about CDN and I think it caused a problem for Mocky.IO 
nothing are worked. 
Error : "Please wait
This application is starting, you will be redirected once it is ready.

If your are the application owner, check your logs for details.
"

**Comment by dougbudadigital** [comment]
Same issue here.
There's some estimated time to get services back?

**Comment by cfrank** [comment]
Hi @julien-lafont - Thank you so much for working on this amazing service! I am encountering the same problem as above. Any update on estimated time to get services restored would be amazing!

Thank you again!

**Comment by julien-lafont** [comment]
Fixed. Thanks bintray for removing all the public repos :)
