### ISSUE TITLE
getting 500s from an endpoint configured to 200

### ISSUE THREAD

**Issue by naugtur** [julien-lafont/Mocky#19]
http://www.mocky.io/v2/57bb70c21000002f175850bd

I configured that one to respond with a 200, but now I'm getting a 500. Is that a hash collision or real server error?

It also doesn't seem to reproduce 100% and seems to depend on client (different browsers, different results)

**Comment by julien-lafont** [comment]
It was a server side issue. Sorry for the inconvenience.
