### ISSUE TITLE
Allow XMLHttpRequest preflight for AJAX requests

### ISSUE THREAD

**Issue by ambrt** [julien-lafont/Mocky#21]
When i try to AJAX to endpoint with 422 HTTP code i get the error:

> XMLHttpRequest cannot load http://www.mocky.io/v2/59089a20250000f90d59e8e5. Response for preflight has invalid HTTP status code 422

It would be nice to allow OPTIONS preflight to be possible with Mocky for AJAX requests with error codes

**Comment by julien-lafont** [comment]
Hello @ambrt 

CORS Preflight requests are now automatically accepted by Mocky.

Thanks for your feedback
