### ISSUE TITLE
Ability to limit to specific verbs

### ISSUE THREAD

**Issue by barnabyc** [julien-lafont/Mocky#32]
I just found this project, wonderfully helpful!

Has there been any thought about limiting which verbs are allowed? Ie. only a PUT, never a POST, etc

Obviously this would require having an error status code response defined as well, so could be non-trivial.

Happy to help if possible - thanks again!

**Comment by julien-lafont** [comment]
A new Mocky version have been released, the code base has been fully rewritten.

I close all previously opened tickets. Feel free to reopen a ticket is your problem is still present.
