### ISSUE TITLE
Enable echo payload

### ISSUE THREAD

**Issue by wtrocki** [julien-lafont/Mocky#33]
Currently in mocky it's not possible to inspect what payload was sent to server.
It will be possible to implement that by adding option to work as echo service and reply payload that was sent to server. 

### Echo parameter

Parameter added to url may ignore defined response and echo request payload.

`PUT https://www.mocky.io/v2/5185415ba171ea3a00704eed?echo=true`

### Echo enabled url

Checkbox when creating url will enable echo service and ignore static json that was defined

Happy to contribute this change.

**Comment by julien-lafont** [comment]
A new Mocky version have been released, the code base has been fully rewritten.

I close all previously opened tickets. Feel free to reopen a ticket is your problem is still present.
