### ISSUE TITLE
Mocky is not working on me. (windows & mac)

### ISSUE THREAD

**Issue by niceman114** [julien-lafont/Mocky#36]
Please see below error information.
How can I fix it??

> [IJ][mocky] $ run
> 
> --- (Running the application, auto-reloading is enabled) ---
> 
> [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
> 
> (Server started, use Enter to stop and go back to the console...)
> 
> [error] 2018-05-03 16:30:34 - application -
> 
> ! @77ni3c27e - Internal server error, for (GET) [/] ->
> 
> play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:
> 
> 1) No implementation for play.modules.reactivemongo.ReactiveMongoApi was bound.
>   while locating play.modules.reactivemongo.ReactiveMongoApi
>     for the 3rd parameter of services.RepositoryDispatcher.<init>(RepositoryDispatcher.scala:13)
>   while locating services.RepositoryDispatcher
>     for the 2nd parameter of controllers.Application.<init>(Application.scala:17)
>   while locating controllers.Application
>     for the 5th parameter of TolerantHttpRequestHandler.<init>(TolerantHttpRequestHandler.scala:14)
>   at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:58):
> Binding(class TolerantHttpRequestHandler to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
> 
> 1 error]
>         at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:186)
>         at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
>         at play.core.server.AkkaHttpServer.modelConversion(AkkaHttpServer.scala:183)
>         at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:189)
>         at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$3(AkkaHttpServer.scala:106)
>         at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
>         at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
>         at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
>         at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
>         at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
>         at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
>         at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
>         at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
>         at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
>         at akka.actor.Actor.aroundReceive(Actor.scala:514)
>         at akka.actor.Actor.aroundReceive$(Actor.scala:512)
>         at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
>         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
>         at akka.actor.ActorCell.invoke(ActorCell.scala:496)
>         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:224)
>         at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
>         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
> 
> 1) No implementation for play.modules.reactivemongo.ReactiveMongoApi was bound.
>   while locating play.modules.reactivemongo.ReactiveMongoApi
>     for the 3rd parameter of services.RepositoryDispatcher.<init>(RepositoryDispatcher.scala:13)
>   while locating services.RepositoryDispatcher
>     for the 2nd parameter of controllers.Application.<init>(Application.scala:17)
>   while locating controllers.Application
>     for the 5th parameter of TolerantHttpRequestHandler.<init>(TolerantHttpRequestHandler.scala:14)
>   at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:58):
> Binding(class TolerantHttpRequestHandler to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
> 
> 1 error
>         at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
>         at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
>         at com.google.inject.Guice.createInjector(Guice.java:99)
>         at com.google.inject.Guice.createInjector(Guice.java:84)
>         at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
>         at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
>         at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
>         at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
>         at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
>         at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:171)
>         ... 25 common frames omitted

**Comment by svilenbs** [comment]
I have the same issue with Ubuntu LTS. Do you have any updates here?

**Comment by julien-lafont** [comment]
A new Mocky version have been released, the code base has been fully rewritten.

I close all previously opened tickets. Feel free to reopen a ticket is your problem is still present.
