### ISSUE TITLE
Ability to use template payloads with given path or query param

### ISSUE THREAD

**Issue by Xanaxiel** [julien-lafont/Mocky#37]
Just thought about this when I encountered the problem for work, the ability to use an existing path/query param's value to populate templates on payload (similar to Postman's handling)

Something like a request of
`GET https://www.mocky.io/v2/5185415ba171ea3a00704eed?foo=value1&bar=value2`

when parsed, will be
`GET https://www.mocky.io/v2/5185415ba171ea3a00704eed?foo=:foo&bar=:bar`

such that when given a response of
```
{ "someKey": ${foo}, "anotherKey": ${bar} }
```

would resolve to
```
{ "someKey": "value1", "anotherKey": "value2" }
```

It could also be used for payload key or value formatting.

**Comment by julien-lafont** [comment]
A new Mocky version have been released, the code base has been fully rewritten.

I close all previously opened tickets. Feel free to reopen a ticket is your problem is still present.
