### ISSUE TITLE
request failing on Android only

### ISSUE THREAD

**Issue by rahul-gharat** [julien-lafont/Mocky#42]
Hi, I am not able to use generated api on android web app. working on IOS and browser.
GET: http://www.mocky.io/v2/5ce3e8733100007e5e742a2e

also not working on Postman REST client with ssl (HTTPS) 
https://www.mocky.io/v2/5ce3e8733100007e5e742a2e

**Comment by julien-lafont** [comment]
A new Mocky version have been released, the code base has been fully rewritten.

I close all previously opened tickets. Feel free to reopen a ticket is your problem is still present.
