### ISSUE TITLE
Ability to Delete the URLs

### ISSUE THREAD

**Issue by sethi3165** [julien-lafont/Mocky#43]
Hi, Is there any way if I can delete the REST URLs which I have mocked  or if I can know that till what time the mocked URL will be live ?

**Comment by SpurguX** [comment]
Yes, it would be good to know how long the URLs are alive. Wondering whether I can rely on a Mocky URL for testing.

**Comment by alexkaufman06** [comment]
I'm also curious about the TTL of mocked URLs.

**Comment by julien-lafont** [comment]
A new version has been release.

You can now delete your (new) mocks. And an expiration option have been added.
Previously created mock doesn't have expiration
