### ISSUE TITLE
Mocky online: Wrong status code in a special case

### ISSUE THREAD

**Issue by Abhith** [julien-lafont/Mocky#46]
**Steps to reproduce**
- Create a 202 response
- After that, duplicate the tab (browser) and create a 200 response (Since the preselected status code on page load is 200, just click generate)
- Check the response status code for the 200, it will be 202.

**Comment by julienlafont-tabmo** [comment]
A new Mocky version have been released, the code base have been fully renewed.

All previously tickets are closed. Feel free to reopen a ticket is your problem is still present.

**Comment by julien-lafont** [comment]
A new Mocky version have been released, the code base has been fully rewritten.

I close all previously opened tickets. Feel free to reopen a ticket is your problem is still present.
