### ISSUE TITLE
JSONP not support numbers

### ISSUE THREAD

**Issue by mikhaili** [julien-lafont/Mocky#47]
In latest version mocky stop support numbers in ?callback=fname1241 <---

not supported ex: https://www.mocky.io/v2/xxxxxx?callback=jQuery1910379398508199031_1591549388376

work ok: https://www.mocky.io/v2/xxxxxx?callback=jQuery

**Comment by julien-lafont** [comment]
Hello.

Thanks for your feedback. I'll fix that quickly

**Comment by julien-lafont** [comment]
Fixed. Such a stupid error ;) https://github.com/julien-lafont/Mocky/commit/3af2e6fe173e0bc3e74e904d77c9c6fccd0c924c

> https://run.mocky.io/v3/9ddfd660-40e6-4900-a7f6-6233f877c10f?callback=$jQuery123456

> $jQuery123456(alert("hello"););

**Comment by mikhaili** [comment]
Thanx you are awesome
