### ISSUE TITLE
Fool proof headers

### ISSUE THREAD

**Issue by sidonaldson** [julien-lafont/Mocky#7]
This is purely a nice to have...

Some people wouldn't understand CORS issues and would want to use Mocky from localhost, the options are there to add the right header in manually but it would be super nice if this one specifically was a checkbox or even just explained in text on the screen.

Access-Control-Allow-Origin: *

Or even send it by default. What do you think?

**Comment by davismj** [comment]
i don't understand the value of mocky if you can't test it from anything other than mocky...

**Comment by studiodev** [comment]
The first usage of Mocky is to mock server-server API, in this use case you doesn't need CORS. So it's not a good idea for me to add it by default.

If you write a JS call, you must be aware of CORS issues to connect the client to your distant API, I think it's good that people issue this problem in the development process.

But I agree that CORS headers are a pain to add if you have to write many routes. Maybe just add a "Enable CORS"' button on the form would be the right solution.

**Comment by sidonaldson** [comment]
@studiodev yes, that's all I mean, adding a button or checkbox will make it super easy for those who do not understand CORS. e.g. if you are locally hosting your site or running js locally without a server you will encounter the CORS error. Just an idea :)

**Comment by voltagex** [comment]
+1 for an "Enable CORS" button.

**Comment by jedrichards** [comment]
I think the solution has to be a bit smarter, mainly for handling non-`200` CORS responses. If I want to simulate a failed `500` response, the responses have to be:

- First a `200` for the preflight `OPTIONS` response
- Then `500` for the actual response

There would have to be some backend code that looked the below pseudo code I guess?

```
if (method === "OPTIONS") send(200)
...
```

**Comment by julien-lafont** [comment]
Hello,

CORS preflight requests are now automatically accepted :)

Thanks for your feedback
