### ISSUE TITLE
Unable to make a new mock if expiry is set to 'Expire in 1 year'

### ISSUE THREAD

**Issue by andresianipar** [julien-lafont/Mocky#82]
Help. Recently I couldn't make a new mock. The application returns an empty response. Here is the screenshoot:

![Screenshot from 2020-07-13 13-38-41](https://user-images.githubusercontent.com/11310372/87278399-90eebb00-c50e-11ea-81ff-5215f2af33f5.png)

This happens if I set expiry to `Expire in 1 year`.

**Comment by julien-lafont** [comment]
Fixed.

Thanks for the reporting.
