### ISSUE TITLE
Request inspection (feature request)

### ISSUE THREAD

**Issue by julian-weinert** [julien-lafont/Mocky#9]
It would be really nice to have request inspection as well.

Below the response field could be a list of incoming requests.
When you click on one of them you can see the complete variety of possible attributes; source IP, headers, body, etc.

**Comment by julien-lafont** [comment]
Hello,

Thanks for you feedback, but I think this feature is "too high level" for a basic tool like Mocky.

For the reference, you can use for example https://requestb.in/ for that.

Thanks for your feedback.
